CREATE TABLE IF NOT EXISTS uc_upload_counts (
    macid VARCHAR(100) NOT NULL,
    sid VARCHAR(255) NOT NULL,
    upload_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (macid, sid),
    INDEX idx_uc_upload_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;