uploads = []
generated = []

[[outputs]]
id = "daFFAykUTiuYXPh0Bgthr"
uri = "file://project_with_db.zip"
type = "unspecified"
title = "Updated ZIP - New Login UI"

[[outputs]]
id = "zCfG8NxV-nie8xeQtX6Bo"
uri = "file://V1.zip"
type = "unspecified"
title = "V1.zip — Latest Project Code"

[[outputs]]
id = "4BOR14aKrFvXgLQRKAL8J"
uri = "file://fixes.zip"
type = "unspecified"
title = "fixes.zip — 3 Updated Files"

[[outputs]]
id = "aShluSKIzJONnITKgoE1U"
uri = "file://aadhaar_test_db.zip"
type = "unspecified"
title = "aadhaar_test_db.zip — MySQL Database Dump"

[[outputs]]
id = "OMM9TLM9p69poC2RQW9XE"
uri = "file://V1_complete.zip"
type = "unspecified"
title = "V1_complete.zip — Full Code + SQL"

[[outputs]]
id = "nQm49oXuj5QV7CUvsvWqI"
uri = "file://mac_fix.zip"
type = "unspecified"
title = "mac_fix.zip — status.php + status_excel.php"

[[outputs]]
id = "y3azQssbqnaBZn26Vrt7B"
uri = "file://status_report_fix.zip"
type = "unspecified"
title = "status_report_fix.zip — mac/status_report.php"
